version: '3.6'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - backend
  payment:
    build:
      context: .
      dockerfile: docker/Dockerfile.payment
    container_name: payment
    volumes:
      - ./services/payment:/go/src
    ports:
      - 50051:50051
    command: bash -c "cd cmd/payment-service && go build main.go && go run main.go"
    depends_on:
      - mysql
    networks:
      - backend
  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    container_name: gateway
    volumes:
      - ./services/gateway:/go/src
    ports:
      - 8000:8000
    environment:
      - PAYMENT_GRPC_SERVER_ENDPOINT=payment:50051
    command: bash -c "cd cmd/gateway-service && go build main.go && go run main.go"
    networks:
      - backend
    depends_on:
      - mysql
  user:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    container_name: user
    volumes:
      - ./services/user:/go/src
    ports:
      - 50052:50052
    command: bash -c "cd cmd/user-service && go build main.go && go run main.go"
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
    name: backend
    driver: bridge
