FROM golang:1.22.7

LABEL maintainer 'Brenddon Anjos <brenddon.dev@gmail.com>'

WORKDIR /go/src

#Migration package
RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest