FROM golang:1.22.7

LABEL maintainer 'Brenddon Anjos <brenddon.dev@gmail.com>'

WORKDIR /go/src

ENV GOOS=linux CGO_ENABLED=1 GOARCH=amd64

#gRPC-Gateway plugin
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest 
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest 
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

CMD ["bash"]