// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type CommerceAiAddress struct {
	ID        int32
	Street    sql.NullString
	Number    sql.NullString
	ZipCode   sql.NullString
	City      sql.NullString
	Country   sql.NullString
	State     sql.NullString
	UserID    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type CommerceAiCard struct {
	ID            int32
	CardName      sql.NullString
	Number        sql.NullString
	HolderName    sql.NullString
	ExpirityMonth sql.NullInt32
	ExpirityYear  sql.NullInt32
	Cvv           sql.NullInt32
	UserID        int32
	AddressID     int32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type CommerceAiCategory struct {
	ID        int32
	Title     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type CommerceAiOrder struct {
	ID        int32
	UserID    int32
	CreatedAt sql.NullTime
	Finished  sql.NullBool
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type CommerceAiOrdersItem struct {
	ID        int32
	Price     sql.NullString
	Amount    sql.NullInt32
	ProductID int32
	OrderID   int32
}

type CommerceAiPayment struct {
	ID           int32
	Type         sql.NullString
	Installments sql.NullInt32
	OrderID      int32
	CardID       int32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type CommerceAiProduct struct {
	ID          int32
	Title       string
	Description sql.NullString
	Barcode     string
	Price       float64
	Amount      int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type CommerceAiProductsCategory struct {
	ID         int32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
	ProductID  int32
	CategoryID int32
}

type CommerceAiUser struct {
	ID        int32
	Name      string
	Username  string
	Email     string
	Password  string
	BirthDate sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
