// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/billing_address.proto

package pb_payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingAddressService_CreateBillingAddress_FullMethodName = "/pb_payment.BillingAddressService/CreateBillingAddress"
)

// BillingAddressServiceClient is the client API for BillingAddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingAddressServiceClient interface {
	CreateBillingAddress(ctx context.Context, in *CreateBillingAddressRequest, opts ...grpc.CallOption) (*BillingAddressResponse, error)
}

type billingAddressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingAddressServiceClient(cc grpc.ClientConnInterface) BillingAddressServiceClient {
	return &billingAddressServiceClient{cc}
}

func (c *billingAddressServiceClient) CreateBillingAddress(ctx context.Context, in *CreateBillingAddressRequest, opts ...grpc.CallOption) (*BillingAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BillingAddressResponse)
	err := c.cc.Invoke(ctx, BillingAddressService_CreateBillingAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingAddressServiceServer is the server API for BillingAddressService service.
// All implementations must embed UnimplementedBillingAddressServiceServer
// for forward compatibility.
type BillingAddressServiceServer interface {
	CreateBillingAddress(context.Context, *CreateBillingAddressRequest) (*BillingAddressResponse, error)
	mustEmbedUnimplementedBillingAddressServiceServer()
}

// UnimplementedBillingAddressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingAddressServiceServer struct{}

func (UnimplementedBillingAddressServiceServer) CreateBillingAddress(context.Context, *CreateBillingAddressRequest) (*BillingAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBillingAddress not implemented")
}
func (UnimplementedBillingAddressServiceServer) mustEmbedUnimplementedBillingAddressServiceServer() {}
func (UnimplementedBillingAddressServiceServer) testEmbeddedByValue()                               {}

// UnsafeBillingAddressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingAddressServiceServer will
// result in compilation errors.
type UnsafeBillingAddressServiceServer interface {
	mustEmbedUnimplementedBillingAddressServiceServer()
}

func RegisterBillingAddressServiceServer(s grpc.ServiceRegistrar, srv BillingAddressServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillingAddressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingAddressService_ServiceDesc, srv)
}

func _BillingAddressService_CreateBillingAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillingAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingAddressServiceServer).CreateBillingAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingAddressService_CreateBillingAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingAddressServiceServer).CreateBillingAddress(ctx, req.(*CreateBillingAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingAddressService_ServiceDesc is the grpc.ServiceDesc for BillingAddressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingAddressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_payment.BillingAddressService",
	HandlerType: (*BillingAddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBillingAddress",
			Handler:    _BillingAddressService_CreateBillingAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/billing_address.proto",
}
